name = "translator"
main = "translator.js"
compatibility_date = "2025-01-01"

# Production environment (default)
kv_namespaces = [
  { binding = "TRANSLATION_CACHE", id = "90eca25c86964d90b4421803ce41094c" }
]

[vars]
ENVIRONMENT = "production"
AZURE_REGION = "eastus"

# Enable observability and logging
[observability]
enabled = true

[observability.logs]
enabled = true

# Production rate limiting bindings
[[unsafe.bindings]]
name = "TRANSLATION_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 3600 }

[[unsafe.bindings]]
name = "AI_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 100, period = 3600 }

[[unsafe.bindings]]
name = "DAILY_TRANSLATION_LIMITER"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 1000, period = 86400 }

[[unsafe.bindings]]
name = "DAILY_AI_LIMITER"
type = "ratelimit"
namespace_id = "1004"
simple = { limit = 500, period = 86400 }

[limits]
cpu_ms = 50

# Development environment
[env.development]
name = "translator-dev"
kv_namespaces = [
  { binding = "TRANSLATION_CACHE", id = "d5bd562d385b4dde947f290af8fe553b" }
]

[env.development.vars]
ENVIRONMENT = "development"
AZURE_REGION = "eastus"

# Development rate limiting bindings (higher limits for testing)
[[env.development.unsafe.bindings]]
name = "TRANSLATION_RATE_LIMITER"
type = "ratelimit"
namespace_id = "2001"
simple = { limit = 1000, period = 3600 }

[[env.development.unsafe.bindings]]
name = "AI_RATE_LIMITER"
type = "ratelimit"
namespace_id = "2002"
simple = { limit = 1000, period = 3600 }

[[env.development.unsafe.bindings]]
name = "DAILY_TRANSLATION_LIMITER"
type = "ratelimit"
namespace_id = "2003"
simple = { limit = 10000, period = 86400 }

[[env.development.unsafe.bindings]]
name = "DAILY_AI_LIMITER"
type = "ratelimit"
namespace_id = "2004"
simple = { limit = 5000, period = 86400 }

[env.development.limits]
cpu_ms = 100  # More generous for dev

[env.development.observability]
enabled = true
head_sampling_rate = 1.0  # Sample all requests in dev