name = "fluent-translator"
main = "translator.js"
compatibility_date = "2025-01-01"

# Account ID (optional - can use CLOUDFLARE_ACCOUNT_ID env var instead)
# account_id = "your-account-id"

# Default KV namespace (for deployments without --env flag)
kv_namespaces = [
  { binding = "TRANSLATION_CACHE", id = "90eca25c86964d90b4421803ce41094c" }
]

[vars]
ENVIRONMENT = "production"
AZURE_REGION = "eastus"

# Enable observability and logging
[observability]
enabled = true

[observability.logs]
enabled = true

# Default rate limiting bindings
[[unsafe.bindings]]
name = "TRANSLATION_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 3600 }

[[unsafe.bindings]]
name = "AI_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 100, period = 3600 }

[[unsafe.bindings]]
name = "DAILY_TRANSLATION_LIMITER"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 1000, period = 86400 }

[[unsafe.bindings]]
name = "DAILY_AI_LIMITER"
type = "ratelimit"
namespace_id = "1004"
simple = { limit = 500, period = 86400 }

# Production environment
[env.production]
name = "fluent-translator"
kv_namespaces = [
  { binding = "TRANSLATION_CACHE", id = "90eca25c86964d90b4421803ce41094c" }
]

[env.production.vars]
ENVIRONMENT = "production"
# AZURE_REGION is set via secrets

# Production rate limiting bindings
[[env.production.unsafe.bindings]]
name = "TRANSLATION_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 3600 }

[[env.production.unsafe.bindings]]
name = "AI_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 100, period = 3600 }

[[env.production.unsafe.bindings]]
name = "DAILY_TRANSLATION_LIMITER"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 1000, period = 86400 }

[[env.production.unsafe.bindings]]
name = "DAILY_AI_LIMITER"
type = "ratelimit"
namespace_id = "1004"
simple = { limit = 500, period = 86400 }

[env.production.limits]
cpu_ms = 50

[env.production.observability]
enabled = true
head_sampling_rate = 0.1  # Sample 10% of requests to manage costs

# Staging environment
[env.staging]
name = "fluent-translator-staging"
kv_namespaces = [
  { binding = "TRANSLATION_CACHE", id = "your-staging-kv-id" }
]

[env.staging.vars]
ENVIRONMENT = "staging"
# AZURE_REGION is set via secrets

# Development environment
[env.development]
name = "fluent-translator-dev"
kv_namespaces = [
  { binding = "TRANSLATION_CACHE", id = "d5bd562d385b4dde947f290af8fe553b" }
]

[env.development.vars]
ENVIRONMENT = "development"
# AZURE_REGION is set via secrets