name = "fluent-translator"
main = "translator-worker.js"
workers_dev = true
compatibility_date = "2023-10-01"

[vars]
TRANSLATOR_REGION = "global"

# For development
[env.development]
vars = { TRANSLATOR_REGION = "global" }

# For production  
[env.production]
vars = { TRANSLATOR_REGION = "global" }

# The worker will be available at fluent-translator.SUBDOMAIN.workers.dev