name = "fluent-translator"
main = "translator-worker.js"
compatibility_date = "2024-01-01"

[vars]
TRANSLATOR_REGION = "global"

# For development
[env.development]
vars = { TRANSLATOR_REGION = "global" }

# For production  
[env.production]
vars = { TRANSLATOR_REGION = "global" }

# Add your routes
routes = [
  { pattern = "fluent-translator.workers.dev", zone_name = "workers.dev" }
]