name: Cloudflare Worker CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'workers/cloudflare/**'
      - '.github/workflows/cloudflare-worker.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'workers/cloudflare/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Test worker build
      working-directory: workers/cloudflare
      run: |
        # Check if worker file exists and is valid
        node -c translator.js
        
        # Check if wrangler.toml is valid
        npx wrangler --version
    
    - name: Validate site configuration
      working-directory: workers/cloudflare
      run: |
        # Check if site-config.json is valid JSON
        node -e "JSON.parse(require('fs').readFileSync('./site-config.json', 'utf8'))"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for Cloudflare secrets
      run: |
        if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
          echo "::error::CLOUDFLARE_API_TOKEN secret is not set. Please add it to your repository secrets."
          echo "See workers/cloudflare/DEPLOYMENT.md for instructions."
          exit 1
        fi
        if [ -z "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]; then
          echo "::error::CLOUDFLARE_ACCOUNT_ID secret is not set. Please add it to your repository secrets."
          echo "You can find your account ID in the Cloudflare dashboard URL or on the right sidebar of any zone."
          exit 1
        fi
        echo "✅ CLOUDFLARE_API_TOKEN is configured"
        echo "✅ CLOUDFLARE_ACCOUNT_ID is configured"
    
    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        workingDirectory: workers/cloudflare
        command: deploy --env production
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        
    - name: Upload site configuration
      if: success()
      working-directory: workers/cloudflare
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        # Only upload if site-config.json has changed
        if git diff --name-only HEAD~1 HEAD 2>/dev/null | grep -q "site-config.json"; then
          echo "Site configuration changed, uploading to KV..."
          node manage-sites.js upload
        else
          echo "No site configuration changes detected"
        fi