name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build extension
        run: npm run package
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "Fluent ${{ github.ref_name }}" \
            --notes "Chrome extension release ${{ github.ref_name }}
          
          ## Installation
          1. Download \`fluent-${{ github.ref_name }}.zip\` from the assets below
          2. Open Chrome and go to \`chrome://extensions/\`
          3. Enable \"Developer mode\"
          4. Drag and drop the zip file onto the page
          
          ## What's New
          - See [commit history](https://github.com/${{ github.repository }}/compare/$(git describe --tags --abbrev=0 2>/dev/null || echo 'HEAD~10')...${{ github.ref_name }}) for changes" \
            ./fluent.zip#fluent-${{ github.ref_name }}.zip